In [3]:
import yfinance as yf

In [36]:
df = yf.download('SPY',period='max')

[*********************100%***********************]  1 of 1 completed

In [37]:
df.index.name

'Date'

In [5]:
df.describe()

Price         Close         High          Low         Open        Volume
Ticker          SPY          SPY          SPY          SPY           SPY
count   8422.000000  8422.000000  8422.000000  8422.000000  8.422000e+03
mean     172.686592   173.646783   171.590573   172.667151  8.308152e+07
std      162.130187   162.891804   161.210954   162.091095  8.920687e+07
min       23.821699    23.890316    23.495844    23.821710  5.200000e+03
25%       70.764355    71.456398    70.264732    70.789155  1.284242e+07
50%       95.896801    96.566580    95.276774    96.025497  6.307505e+07
75%      232.829269   234.713288   230.627243   232.785026  1.102586e+08
max      757.618225   758.446109   754.805464   756.201867  8.710263e+08

In [6]:
df.head()

Price           Close       High        Low       Open   Volume
Ticker            SPY        SPY        SPY        SPY      SPY
Date
1993-01-29  24.113260  24.130411  24.010359  24.130411  1003200
1993-02-01  24.284760  24.284760  24.130407  24.130407   480500
1993-02-02  24.336208  24.353359  24.216157  24.267607   201300
1993-02-03  24.593479  24.610629  24.353375  24.370526   529400
1993-02-04  24.696365  24.747816  24.404811  24.679215   531500

In [14]:
df.columns

MultiIndex([( 'Close', 'SPY'),
            (  'High', 'SPY'),
            (   'Low', 'SPY'),
            (  'Open', 'SPY'),
            ('Volume', 'SPY')],
           names=['Price', 'Ticker'])

In [17]:
df.shape

(8422, 5)

In [22]:
df.iloc[-1]

Price   Ticker
Close   SPY       7.489300e+02
High    SPY       7.545700e+02
Low     SPY       7.484000e+02
Open    SPY       7.527600e+02
Volume  SPY       3.028198e+07
Name: 2026-07-16 00:00:00, dtype: float64

In [23]:
df.columns = df.columns.get_level_values(0)

In [24]:
df.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='str', name='Price')

In [27]:
df.columns.to_list()

['Close', 'High', 'Low', 'Open', 'Volume']

In [28]:
df.reset_index()

Price       Date       Close        High         Low        Open    Volume
0     1993-01-29   24.113260   24.130411   24.010359   24.130411   1003200
1     1993-02-01   24.284760   24.284760   24.130407   24.130407    480500
2     1993-02-02   24.336208   24.353359   24.216157   24.267607    201300
3     1993-02-03   24.593479   24.610629   24.353375   24.370526    529400
4     1993-02-04   24.696365   24.747816   24.404811   24.679215    531500
...          ...         ...         ...         ...         ...       ...
8417  2026-07-10  754.950012  755.419983  748.099976  752.049988  42191300
8418  2026-07-13  749.169983  753.909973  748.000000  752.469971  44013600
8419  2026-07-14  751.830017  753.340027  748.659973  750.909973  35143100
8420  2026-07-15  754.809998  755.580017  750.200012  754.239990  43844800
8421  2026-07-16  748.929993  754.570007  748.400024  752.760010  30281982

[8422 rows x 6 columns]

In [32]:
df = df.reset_index()

In [34]:
df['ticker'] = 'SPY'

In [35]:
df.columns.to_list()

['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'ticker']